name: Invoke updateFiles on deployment managed by Cloudsoft AMP

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env: # Or as an environment variable
      AMP_PASSWORD: ${{ secrets.AMP_PASSWORD }}
    steps:
      - name: Invoke updateFiles effector using curl
        run: |
           curl -u admin:${AMP_PASSWORD} -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' http://52.50.105.96:8081/v1/applications/tijr68g4zs/entities/r11w2vandx/effectors/updateFiles

